#!/usr/bin/env python3

import datetime
import subprocess

import rospy
from std_msgs.msg import String


class RosbagRecorder:

    def __init__(self):
        self.summary_process = None  # recording the summary ROSBag: positions, compressed video
        self.video_process = None  # recording the full resolution main camera
        self.is_recording = False


    def argos3_status_callback(self, data):
        if data.data == "Started":
            self.start_recording()
        elif data.data == "Stopped":
            self.stop_recording()
        else:
            rospy.logwarn(f"{rospy.get_caller_id()}: Unknown message body {data.data}")
    
    def start_recording(self):
        if self.is_recording:
            rospy.logwarn(f"{rospy.get_caller_id()}: Node is already recording")
            return
        rospy.loginfo(f"{rospy.get_caller_id()}: Starting recording")
        self.is_recording = True
        self.summary_process = subprocess.Popen(["rosbag", "record", "-O", f"tycho-experiment-{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}-summary.bag", "-e", "/camera_(.)/camera/image_rect_color/compressed", "-e", "/camera_(.)/camera/camera_info", "-e", "/epuck_(.*)/odometry/filtered"])
        self.video_process = subprocess.Popen(["rosbag", "record", "-O", f"tycho-experiment-{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}-video.bag", "-e", "/camera_2/camera/image_rect_color", "-e", "/camera_(.)/camera/camera_info"])
    
    def stop_recording(self):
        if not self.is_recording:
            return
        rospy.loginfo(f"{rospy.get_caller_id()}: Stopping recording")
        self.is_recording = False
        self.summary_process.terminate()
        self.video_process.terminate()
    
def start_listening():
    # In ROS, nodes are uniquely named. If two nodes with the same
    # name are launched, the previous one is kicked off. The
    # anonymous=True flag means that rospy will choose a unique
    # name for our 'listener' node so that multiple listeners can
    # run simultaneously.
    rospy.init_node('tycho_recorder_node', anonymous=True)
    recorder = RosbagRecorder()
    rospy.Subscriber("/argos3/status", String, recorder.argos3_status_callback)
    rospy.on_shutdown(recorder.stop_recording)
    rospy.loginfo(f"{rospy.get_caller_id()}: Node is ready for recording.")
    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()

if __name__ == '__main__':
    start_listening()
